apiVersion: apps/v1
kind: Deployment
metadata:
  name: authing-gateway
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authing-gateway
  template:
    metadata:
      labels:
        app: authing-gateway
    spec:
      containers:
      - name: authing-gateway
        image: uhub.service.ucloud.cn/entropypool/authing-gateway:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: authing-gateway
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 50250
    targetPort: 50250
  - name: grpc
    port: 50251
    targetPort: 50251
  - name: prometheus
    port: 50252
    targetPort: 50252
  selector:
    app: authing-gateway
